services:
  - type: web
    name: client-frontend
    env: static
    buildCommand: npm run build
    staticPublishPath: dist
    rootDir: client

  - type: web
    name: admin-dashboard
    env: static
    buildCommand: npm run build
    staticPublishPath: dist
    rootDir: admin

  - type: web
    name: backend-api
    env: node
    buildCommand: npm install
    startCommand: node server.js
    rootDir: backend
    envVars:
      - key: NODE_ENV
        value: production
      - key: API_KEY
        value: YOUR_API_KEY
